### ISSUE TITLE
Monitoring file needs capping

### ISSUE THREAD

**Issue by zwxw7967** [Orange-OpenSource/cppuprofile#13]
I notice that monitoring file size could be very huge (more than 25 MB) after my application has been running for several hours (configuring CPU & GPU monitoring with a 200 ms period).

Unfortunately it causes some freezes (or crashes) because in my context, the location of the monitoring file is in RAM (/var/log) and my system has limited RAM.

Thus, it would be nice to have a mechanism that limit the monitoring file size, with new API (ou new arg in existing API) to configure the limit for the max file size (or max line count).

In my use case, I only need to analyze last lines for a limited duration (less than a hour), so a simple circular buffer is appropriate for me (with unique file, removing older line when adding new line after capping is reached). 
Another option (probably more efficient) could be to write in several capped files (uprofile_0.log, uprofile_1.log, uprofile_2.log, overriding uprofile_0.log when uprofile._2.log is full).

Thanks,
Fabien

**Comment by cedric-chedaleux** [comment]
Hello @zwxw7967 

Thanks for the feedback and the suggestion.

I will definitely add a new API to cap the file size and prevent the system from running out of memory due to unbounded profiling log. 

I'll probably use two rotating files instead of a single circular one which would require the usage of a temporary file or re-write the whole content without the first line when adding a new line...
